---

galaxy_info:
  author: Ilkka Tengvall
  description: Role sets up container(s) to run on host with help of systemd.
  company: Red Hat
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - 8
        - 7
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
        - disco
        - eoan
        - focal
  galaxy_tags:
    - podman
    - container
    - systemd

collections:
  - containers.podman
