---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ memcached_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - memcached
  register: container_facts
  when: kolla_container_engine == 'docker'

- name: Get container facts
  become: true
  kolla_container_facts_podman:
    name:
      - memcached
  register: container_facts
  when: kolla_container_engine == 'podman'

- name: Checking free port for Memcached
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ memcached_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['memcached'] is not defined
    - inventory_hostname in groups['memcached']
