---
- import_tasks: config.yml

- import_tasks: check-containers.yml
  when: kolla_container_engine == 'docker'

- import_tasks: check-containers-podman.yml
  when: kolla_container_engine == 'podman'

- include_tasks: clone.yml
  when:
    - keystone_dev_mode | bool

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers

- include_tasks: distribute_fernet.yml
  when:
    - keystone_token_provider == 'fernet'

- import_tasks: register.yml

- import_tasks: check.yml

- include_tasks: register_identity_providers.yml
  when:
    - enable_keystone_federation | bool
