---
- import_tasks: register.yml

- include_tasks: clone.yml
  when: placement_dev_mode | bool

- import_tasks: config.yml

- import_tasks: check-containers.yml
  when: kolla_container_engine == 'docker'

- import_tasks: check-containers-podman.yml
  when: kolla_container_engine == 'podman'

- import_tasks: bootstrap_docker.yml
  when: kolla_container_engine == 'docker'

- import_tasks: bootstrap_podman.yml
  when: kolla_container_engine == 'podman'

- name: Flush handlers
  meta: flush_handlers
