---
- name: Deploy horizon container
  vars:
    container_image_list:
      - "{{ horizon_services.horizon.image }}"
    container_name: "{{ horizon_services.horizon.container_name }}"
    container_run_args: >-
      --label "io.containers.autoupdate=image"
      -v "{{ node_config_directory }}/horizon/:{{ container_config_directory }}/:ro"
      -v "/etc/localtime:/etc/localtime:ro"
      -v "kolla_logs:/var/log/kolla"
      -v "/tmp:/tmp"
      --env KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      --env ENABLE_BLAZAR="{{ 'yes' if enable_horizon_blazar | bool else 'no' }}"
      --env ENABLE_CLOUDKITTY="{{ 'yes' if enable_horizon_cloudkitty | bool else 'no' }}"
      --env ENABLE_DESIGNATE="{{ 'yes' if enable_horizon_designate | bool else 'no' }}"
      --env ENABLE_FREEZER="{{ 'yes' if enable_horizon_freezer | bool else 'no' }}"
      --env ENABLE_HEAT="{{ 'yes' if enable_horizon_heat | bool else 'no' }}"
      --env ENABLE_IRONIC="{{ 'yes' if enable_horizon_ironic | bool else 'no' }}"
      --env ENABLE_MAGNUM="{{ 'yes' if enable_horizon_magnum | bool else 'no' }}"
      --env ENABLE_MANILA="{{ 'yes' if enable_horizon_manila | bool else 'no' }}"
      --env ENABLE_MASAKARI="{{ 'yes' if enable_horizon_masakari | bool else 'no' }}"
      --env ENABLE_MISTRAL="{{ 'yes' if enable_horizon_mistral | bool else 'no' }}"
      --env ENABLE_MONASCA="{{ 'yes' if enable_horizon_monasca | bool else 'no' }}"
      --env ENABLE_MURANO="{{ 'yes' if  enable_horizon_murano | bool else 'no' }}"
      --env ENABLE_NEUTRON_VPNAAS="{{ 'yes' if enable_horizon_neutron_vpnaas | bool else 'no' }}"
      --env ENABLE_OCTAVIA="{{ 'yes' if enable_horizon_octavia | bool else 'no' }}"
      --env ENABLE_SAHARA="{{ 'yes' if enable_horizon_sahara | bool else 'no' }}"
      --env ENABLE_SENLIN="{{ 'yes' if enable_horizon_senlin | bool else 'no' }}"
      --env ENABLE_SOLUM="{{ 'yes' if enable_horizon_solum | bool else 'no' }}"
      --env ENABLE_TACKER="{{ 'yes' if enable_horizon_tacker | bool else 'no' }}"
      --env ENABLE_TROVE="{{ 'yes' if enable_horizon_trove | bool else 'no' }}"
      --env ENABLE_VITRAGE="{{ 'yes' if enable_horizon_vitrage | bool else 'no' }}"
      --env ENABLE_WATCHER="{{ 'yes' if enable_horizon_watcher | bool else 'no' }}"
      --env ENABLE_ZUN="{{ 'yes' if enable_horizon_zun | bool else 'no' }}"
      --env FORCE_GENERATE="{{ 'yes' if horizon_dev_mode | bool else 'no' }}"
      --privileged
      --network host
    container_state: running
  include_role:
    name: podman-container-systemd
  when:
    - inventory_hostname in groups[horizon_services.horizon.group]
    - horizon_services.horizon.enabled | bool
