---
- name: Restart rabbitmq container
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    #action: "recreate_or_restart_container"
    #common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes }}"
    env: "{{ service.environment }}"
    #dimensions: "{{ service.dimensions }}"

- name: Waiting for rabbitmq to start
  vars:
    service_name: "rabbitmq"
    service: "{{ rabbitmq_services[service_name] }}"
  become: true
  command: "podman exec {{ service.container_name }} rabbitmqctl wait {{ rabbitmq_pid_file }}"
