---
- name: Restart heat-api container
  vars:
    service_name: "heat-api"
    service: "{{ heat_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    network: "host"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"

- name: Restart heat-api-cfn container
  vars:
    service_name: "heat-api-cfn"
    service: "{{ heat_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    network: "host"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"

- name: Restart heat-engine container
  vars:
    service_name: "heat-engine"
    service: "{{ heat_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    network: "host"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
