---
- name: Restart nova-super-conductor container
  vars:
    service_name: "nova-super-conductor"
    service: "{{ nova_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    network: "host"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - kolla_action != "upgrade" or not nova_safety_upgrade | bool

- name: Restart nova-scheduler container
  vars:
    service_name: "nova-scheduler"
    service: "{{ nova_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    network: "host"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - kolla_action != "upgrade" or not nova_safety_upgrade | bool

- name: Restart nova-api container
  vars:
    service_name: "nova-api"
    service: "{{ nova_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    state: started
    restart: yes
    network: "host"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - kolla_action != "upgrade" or not nova_safety_upgrade | bool
