---
- name: Initializing toolbox container using normal user
  become: true
  command: "{{kolla_container_engine}} exec -t {{ common_services['kolla-toolbox']['container_name'] }} ansible --version"
  changed_when: false

- import_tasks: main-docker.yml
  when: kolla_container_engine == 'docker'
  
- import_tasks: main-podman.yml
  when: kolla_container_engine == 'podman'
