---
# - name: Check chrony container
#   become: true
#   containers.podman.podman_container:
#     name: "{{ dict_item.value.container_name }}"
#     image: "{{ dict_item.value.image }}"
#     privileged: "{{ dict_item.value.privileged }}"
#     volumes: "{{ dict_item.value.volumes }}"
#     network: "host"
#     env:
#       KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
#   when:
#     - inventory_hostname in groups[dict_item.value.group]
#     - dict_item.value.enabled | bool
#   with_dict: "{{ chrony_services }}"

- name: Create service
  vars:
    container_image_list: 
      - "{{ dict_item.value.image }}"
    container_name: "{{ dict_item.value.container_name }}"
    container_run_args: >-
      --label "io.containers.autoupdate=image"
      -v "{{ node_config_directory }}/chrony/:{{ container_config_directory }}/:ro"
      -v "/etc/localtime:/etc/localtime:ro"
      -v "kolla_logs:/var/log/kolla"
      --env KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      --privileged
      --network host
    container_state: running
  include_role:
    name: podman-container-systemd
  when:
    - inventory_hostname in groups[dict_item.value.group]
    - dict_item.value.enabled | bool
  with_dict: "{{ chrony_services }}"
  loop_control:
    loop_var: dict_item