---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ magnum_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - magnum_api
  register: container_facts
  when: kolla_container_engine == 'docker'

- name: Get container facts
  become: true
  kolla_container_facts_podman:
    name:
      - magnum_api
  register: container_facts
  when: kolla_container_engine == 'podman'

- name: Checking free port for Magnum API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ magnum_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['magnum_api'] is not defined
    - inventory_hostname in groups['magnum-api']
