---
- name: Restart horizon container
  vars:
    service_name: "horizon"
    service: "{{ horizon_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    environment: "{{ service.environment }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - kolla_container_engine == 'docker'

- name: Restart horizon container Podman
  vars:
    service_name: "horizon"
    service: "{{ horizon_services[service_name] }}"
  become: true
  containers.podman.podman_container:
    force_restart: yes
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    env: "{{ service.environment }}"
    volumes: "{{ service.volumes }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - kolla_container_engine == 'podman'
