---

- name: Stop backup keepalived container
  become: true
  kolla_docker:
    action: "stop_container"
    # NOTE(yoctozepto): backup node might not have keepalived yet - ignore
    ignore_missing: true
    common_options: "{{ docker_common_options }}"
    name: "keepalived"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_False is defined
    - inventory_hostname in groups.kolla_ha_is_master_False
  listen:
    - Restart keepalived container

- name: Restart backup haproxy container
  vars:
    service_name: "haproxy"
    service: "{{ haproxy_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_False is defined
    - inventory_hostname in groups.kolla_ha_is_master_False
  listen:
    - Restart haproxy container
    - Restart keepalived container
  notify:
    - Wait for backup haproxy to start

- name: Start backup keepalived container
  vars:
    service_name: "keepalived"
    service: "{{ haproxy_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_False is defined
    - inventory_hostname in groups.kolla_ha_is_master_False
  listen:
    - Restart keepalived container
  notify:
    - Wait for virtual IP to appear

# NOTE(yoctozepto): This is to ensure haproxy can close any open connections
# to the VIP address.
- name: Stop master haproxy container
  become: true
  kolla_docker:
    action: "stop_container"
    common_options: "{{ docker_common_options }}"
    name: "haproxy"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_True is defined
    - inventory_hostname in groups.kolla_ha_is_master_True
  listen:
    - Restart keepalived container

- name: Stop master keepalived container
  become: true
  kolla_docker:
    action: "stop_container"
    common_options: "{{ docker_common_options }}"
    name: "keepalived"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_True is defined
    - inventory_hostname in groups.kolla_ha_is_master_True
  listen:
    - Restart keepalived container

- name: Start master haproxy container
  vars:
    service_name: "haproxy"
    service: "{{ haproxy_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
    healthcheck: "{{ service.healthcheck | default(omit) }}"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_True is defined
    - inventory_hostname in groups.kolla_ha_is_master_True
  listen:
    - Restart haproxy container
    - Restart keepalived container
  notify:
    - Wait for master haproxy to start

- name: Start master keepalived container
  vars:
    service_name: "keepalived"
    service: "{{ haproxy_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged | default(False) }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - groups.kolla_ha_is_master_True is defined
    - inventory_hostname in groups.kolla_ha_is_master_True
  listen:
    - Restart keepalived container
  notify:
    - Wait for virtual IP to appear
