---
- import_tasks: register.yml

- import_tasks: config.yml

- import_tasks: check-containers.yml
  when: kolla_container_engine == 'docker'
  
- import_tasks: check-containers-podman.yml
  when: kolla_container_engine == 'podman'

- include_tasks: clone.yml
  when:
    - heat_dev_mode | bool

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers
