---
- name: Destroying all Kolla containers and volumes
  script: ../tools/cleanup-containers
  when: kolla_container_engine == 'docker'

- name: Destroying all Kolla containers and volumes (podman)
  script: ../tools/cleanup-containers-podman
  when: kolla_container_engine == 'podman'
